### ISSUE TITLE
Move master to 4.x

### ISSUE THREAD

**Issue by lleger** [trptcolin/consistency_fail#25]
While working on #24, I realized the codebase still works against ActiveRecord 3.x, which is no longer [maintained](http://guides.rubyonrails.org/maintenance_policy.html). This is a problem when running against Ruby 2.2 (you get a `circular argument reference - now` warning in ActiveSupport), because there's a [bug that will go unfixed](https://github.com/rails/rails/pull/18160). I would recommend moving the current codebase (perhaps, even, without #24) to a `3-2-stable` branch and moving master to 4.x compatibility, to stay tracked with Rails.

**Comment by trptcolin** [comment]
:+1:

**Comment by shadowbq** [comment]
With release of Rails 5 imminent (http://weblog.rubyonrails.org/2015/12/18/Rails-5-0-beta1/) what is the status of this gem? Why is it still tracking 3.x ?

**Comment by trptcolin** [comment]
Just merged all pending PRs. I'd be happy to get a patch for 4.x & 5.x support!

**Comment by dijonkitchen** [comment]
👍

**Comment by trptcolin** [comment]
I was able to make some time today to take a look at Rails 4.x & 5.x. It looks like these mostly already work. There's an issue with views in Rails 4, and I've added language to the README to describe that issue:

> The known issue with views in ActiveRecord 4.x is that in this version, the connection adapter's tables method includes both tables and views. This means that without additional monkeypatches to the various connection adapters, we cannot reliably detect whether a given model is backed by a table or a view. I wouldn't mind monkeypatching a bounded set of adapters, but I don't want to be on the hook for arbitrary connection adapters that may require licenses to test (e.g. SQL Server, Oracle).

I think the best approach there is going to be the same as in #34, adding a way for end users to ignore specific index suggestions. I'd love to get a PR for that.

I'm going to close this, but please do open issues for additional specific problems with Rails 4/5 integration.
